stages:
  - build
  - deploy

build:go_api:
  stage: build
  script:
    - apt update
    - apt install -y golang
    - cd src
    - go build server.go
  artifacts:
    paths:
      - /builds/homelab-group/golisp/src/server
    expire_in: 1 days

build:angular_frontend:
  stage: build
  script:
    - apt update
    - apt install -y nodejs npm
    - npm install -g @angular/cli@12
    - cd webapp
    - ng build --prod
  artifacts:
    paths:
      - /builds/homelab-group/golisp/webapp/dist
    expire_in: 1 days

deploy:go_api:
  stage: deploy
  script:
    - apt update
    - echo "plop"

deploy:angular_frontend:
  stage: deploy
  script:
    - apt update
    - echo "plop"
