stages:
  - build
  - deploy

build:go_api:
  stage: build
  script:
    - apt update
    - apt install -y golang
    - cd src
    - sleep 3600
 artifacts:
    paths:
      - /builds/badock/homelab-group/golisp/src/golang_bin
    expire_in: 1 days

build:angular_frontend:
  stage: build
  script:
    - apt update
    - apt install -y python3 python3-pip
    - npm install -g @angular/cli@12
    - cd webapp
    - sleep 3600
    - ng build --prod
 artifacts:
    paths:
      - /builds/badock/homelab-group/golisp/webapp/dist
    expire_in: 1 days

deploy:go_api:
  stage: deploy
  script:
    - apt update
    - echo "plop"

deploy:angular_frontend:
  stage: deploy
  script:
    - apt update
    - echo "plop"
