stages:
  - build
  - deploy
  - pages

build:go_api:
  stage: build
  script:
    - apt update
    - apt install -y golang
    - cd src
    - go build server.go
  artifacts:
    paths:
      - /builds/homelab-group/golisp/src/server
    expire_in: 1 days

build:angular_frontend:
  stage: build
  script:
    - apt update
    - apt install -y nodejs npm
    - npm install -g @angular/cli@11
    - cd webapp
    - npm install .
    - ng build --prod
  artifacts:
    paths:
      - /builds/homelab-group/golisp/webapp/dist
    expire_in: 1 days

deploy:go_api:
  stage: deploy
  script:
    - ssh s2.jonathanpastor.fr 'supervisorctl stop golisp_api'
    - scp /builds/homelab-group/golisp/src/server s2.jonathanpastor.fr:/root/golisp/src/plop
    - ssh s2.jonathanpastor.fr 'supervisorctl start golisp_api'

pages:
  stage: deploy
  script:
  - apt update
  - apt install -y rsync

  - mkdir -p public
  - rsync -avz --progress /builds/homelab-group/golisp/webapp/dist public/

  environment:
    name: docs
    # Ask gitlab pages to deploy the public folder in specific URL that contains the branch name
    url: https://badock.gitlab.io/homelab-group/golisp
  artifacts:
    paths:
    - public
    expire_in: 1 week
